"""initial_migration

Revision ID: 0bc908e76bef
Revises: 
Create Date: 2026-08-04 07:21:03.210935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc908e76bef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fotografias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_envio', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('arquivo', sa.LargeBinary(), nullable=False),
    sa.Column('foto_de_evento', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade_saude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lotacao', sa.Integer(), nullable=False),
    sa.Column('tempo_medio_atendimento', sa.Integer(), nullable=True),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario_administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('foto_perfil', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foto_perfil'], ['fotografias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario_comum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('foto_perfil', sa.Integer(), nullable=True),
    sa.Column('regiao_preferida', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['foto_perfil'], ['fotografias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario_institucional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('vinculo_instituicao', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('foto_perfil', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['foto_perfil'], ['fotografias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_hora_evento', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('publico_alvo', sa.String(), nullable=False),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('foto_evento', sa.Integer(), nullable=False),
    sa.Column('criador_institucional', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
    sa.Column('unidade_associada', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('data_hora_cancelamento', sa.DateTime(), nullable=True),
    sa.Column('data_hora_ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('pagina_evento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['criador_institucional'], ['usuario_institucional.id'], ),
    sa.ForeignKeyConstraint(['foto_evento'], ['fotografias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('sugestao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('data_hora_envio', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario'], ['usuario_comum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_feito', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario_comum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario_comum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscricao')
    op.drop_table('comentario')
    op.drop_table('sugestao')
    op.drop_table('evento')
    op.drop_table('usuario_institucional')
    op.drop_table('usuario_comum')
    op.drop_table('usuario_administrador')
    op.drop_table('unidade_saude')
    op.drop_table('fotografias')
    op.drop_table('categoria')
    # ### end Alembic commands ###
