"""adicao de regiao

Revision ID: 6cd9d8beeb3a
Revises: a472ecb1d930
Create Date: 2026-10-09 11:21:59.551806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd9d8beeb3a'
down_revision: Union[str, Sequence[str], None] = 'a472ecb1d930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotografias', schema=None) as batch_op:
        batch_op.alter_column('caminho',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('tamanho',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotografias', schema=None) as batch_op:
        batch_op.alter_column('tamanho',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('caminho',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
