"""criar_tabela_evento

Revision ID: 9c6097110d9c
Revises: 
Create Date: 2026-07-11 08:41:43.941538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6097110d9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('usuario_criador', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.Integer(), nullable=False),
    sa.Column('foto_evento', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('unidade_associada', sa.Integer(), nullable=True),
    sa.Column('data_cancelamento', sa.Date(), nullable=True),
    sa.Column('data_ultima_atualizacao', sa.Date(), nullable=True),
    sa.Column('link_externo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Evento')
    # ### end Alembic commands ###
