"""criacao_de_fotografia_categoria_ajustes_em_eventos

Revision ID: c5e6f94b26d2
Revises: 9c6097110d9c
Create Date: 2026-07-15 10:10:26.820175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e6f94b26d2'
down_revision: Union[str, Sequence[str], None] = '9c6097110d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fotografias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_envio', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('arquivo', sa.LargeBinary(), nullable=False),
    sa.Column('foto_de_evento', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Evento')
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('criador_institucional', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_hora_evento', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('publico_alvo', sa.String(), nullable=False),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('foto_evento', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
    sa.Column('unidade_associada', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('data_cancelamento', sa.DateTime(), nullable=True),
    sa.Column('data_ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('pagina_evento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['foto_evento'], ['fotografias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Evento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_criacao', sa.DATE(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('titulo', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('usuario_criador', sa.INTEGER(), nullable=False),
    sa.Column('tipo_evento', sa.INTEGER(), nullable=False),
    sa.Column('foto_evento', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=True),
    sa.Column('capacidade_maxima', sa.INTEGER(), nullable=True),
    sa.Column('endereco', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('unidade_associada', sa.INTEGER(), nullable=True),
    sa.Column('data_cancelamento', sa.DATE(), nullable=True),
    sa.Column('data_ultima_atualizacao', sa.DATE(), nullable=True),
    sa.Column('link_externo', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.drop_table('evento')
    op.drop_table('fotografias')
    op.drop_table('categoria')
    # ### end Alembic commands ###
