"""att_do_banco

Revision ID: e76c1e177db5
Revises: c5e6f94b26d2
Create Date: 2026-07-24 17:49:45.632662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76c1e177db5'
down_revision: Union[str, Sequence[str], None] = 'c5e6f94b26d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidade_saude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lotacao', sa.Integer(), nullable=False),
    sa.Column('tempo_medio_atendimento', sa.Integer(), nullable=True),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario_administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=False),
    sa.Column('foto_perfil', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foto_perfil'], ['fotografias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario_comum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=False),
    sa.Column('foto_perfil', sa.Integer(), nullable=True),
    sa.Column('regiao_preferida', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['foto_perfil'], ['fotografias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario_institucional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('vinculo_instituicao', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('foto_perfil', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['foto_perfil'], ['fotografias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('sugestao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('data_hora_envio', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario'], ['usuario_comum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_feito', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario_comum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario_comum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora_cancelamento', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario_institucional', ['criador_institucional'], ['id'])
        batch_op.drop_column('data_cancelamento')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cancelamento', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_hora_cancelamento')

    op.drop_table('inscricao')
    op.drop_table('comentario')
    op.drop_table('sugestao')
    op.drop_table('usuario_institucional')
    op.drop_table('usuario_comum')
    op.drop_table('usuario_administrador')
    op.drop_table('unidade_saude')
    # ### end Alembic commands ###
